# Generated by Django 4.1.6 on 2023-02-09 14:41

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
