# Generated by Django 4.1.6 on 2023-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewCount',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
