# Generated by Django 4.1.6 on 2023-02-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_post_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
