# Generated by Django 4.1.6 on 2023-02-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_imagepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='default',
            new_name='main_image',
        ),
    ]
