# Generated by Django 4.1.6 on 2023-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_rename_default_imagepost_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
