# Generated by Django 4.1.6 on 2023-02-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_alter_userprofile_last_name_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
